# Generated by Django 3.1.1 on 2020-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('birth', models.DateTimeField(verbose_name='birth')),
                ('cep', models.CharField(max_length=8, verbose_name='cep')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('home_number', models.CharField(max_length=10, verbose_name='home_number')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='neighborhood')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('phone', models.CharField(max_length=50, verbose_name='phone_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
