# Generated by Django 3.1.1 on 2020-09-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=11, verbose_name='phone_number'),
        ),
    ]
